// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgvAzyM1vBsv5J8-ZDGTfrJSmXLrSbdDw',
    appId: '1:222756011492:web:200f4fcec32317e01bdbf1',
    messagingSenderId: '222756011492',
    projectId: 'financeapp-6dcee',
    authDomain: 'financeapp-6dcee.firebaseapp.com',
    storageBucket: 'financeapp-6dcee.appspot.com',
    measurementId: 'G-GW8L2X82FJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClEXejW62v5lsjF_Yvtdb_uhLTwmmcL8Y',
    appId: '1:222756011492:android:f91e978109fbcea91bdbf1',
    messagingSenderId: '222756011492',
    projectId: 'financeapp-6dcee',
    storageBucket: 'financeapp-6dcee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxtgKungyliruUvtbR6pSfBVNavlA461A',
    appId: '1:222756011492:ios:ae5c2049b51cc1a11bdbf1',
    messagingSenderId: '222756011492',
    projectId: 'financeapp-6dcee',
    storageBucket: 'financeapp-6dcee.appspot.com',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxtgKungyliruUvtbR6pSfBVNavlA461A',
    appId: '1:222756011492:ios:5ee0d1dbb7f790d31bdbf1',
    messagingSenderId: '222756011492',
    projectId: 'financeapp-6dcee',
    storageBucket: 'financeapp-6dcee.appspot.com',
    iosBundleId: 'com.example.financeApp.RunnerTests',
  );
}
